### ISSUE TITLE
PHP Fatal error:  Class 'StaticHtmlOutput' not found

### ISSUE THREAD

**Issue by rollecode** [astorm/wp-static-html-output-plugin#2]
Using native [macOS LEMP stack](https://github.com/digitoimistodude/osx-lemp-setup) (installed via Homebrew), php7.0 at /usr/local/bin/php version:

```
php --version
PHP 7.0.23 (cli) (built: Sep 25 2017 08:07:03) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
```

Getting following:

```
➜  airdev wp static-html-output generate http://airdev.test
PHP Fatal error:  Class 'StaticHtmlOutput' not found in /Users/rolle/.wp-cli/packages/vendor/pulsestorm/wp-static-html-output-plugin/library.php on line 2
Fatal error: Class 'StaticHtmlOutput' not found in /Users/rolle/.wp-cli/packages/vendor/pulsestorm/wp-static-html-output-plugin/library.php on line 2
```

Any idea on how to solve?

**Comment by astorm** [comment]
@ronilaukkarinen Thanks for you interest in this project!  

What version of wp-cli and static-html-output are you using? We ask because we haven't kept up wither either version

    $ wp --version
    WP-CLI 0.24.1

    $ cat wp-static-html-output.php | grep Version
    Version:     1.1.1

and I bet that the static output plugin has been changed recently such that there's no longer a class named `StaticHtmlOutput`.

We're open to fixing thing and bringing the plugin up to date -- unfortunately we've had other priorities and there's only do many open source projects we can take on.

Also -- question: It looks like you're running your commands through a command named `airdev`.  What is this? (or is that just your prompt?)

**Comment by rollecode** [comment]
Sorry for not being careful, forgot the most important versions! Also, my prompt is a bit funny, airdev is the name of the current directory. See here:

![Screenshot](https://rolle.wtf/wp-cli-static-html.png "Screenshot")

**Comment by rollecode** [comment]
Oh... I see what I did. Didn't have the WordPress plugin installed. Assumed this wp-cli plugin works out of the box without separate plugin... I don't know why, because I use wp-cli a lot and know it only communicates with WordPress. My bad, too sleep deprived. Seems to work fine after installing and configuring the plugin. Sorry for the hassle!
