### ISSUE TITLE
Automation issue in Version 5.8

### ISSUE THREAD

**Issue by Rapitharian** [astorm/wp-static-html-output-plugin#3]
I am running Version 5.8 Pro of the plugin.
When I use the server side hook to have the plugin generate the static HTML it never completes.  It creates the basic directories but none of the site specific folders.

When I manually run the generation of the files the system completes in 23 minutes and generates a zip file.
Let me know what diagnosis information you require and I will retrieve it.
I am running: Redhat 7, Latest Wordpress, PHP 7.2, I use the Avada theme.

**Comment by Rapitharian** [comment]
The folders created as the "basic directories" are as follows:
author
category
comments
feed
index.html
wp-content
wp-includes
wp-json

**Comment by astorm** [comment]
@Rapitharian Thanks for giving this code a try -- unfortunately, this isn't something I actively maintain.  I wrote it for a purpose, it did that purpose, and I open sourced it in case someone else might find it useful.  I wouldn't begin to know what sort of diagnostic information to ask for because I remember how all this works.  Happy to accept PRs, but I'm afraid I can't help you directly. 

Best wishes.
